# type: ignore
# pylint: skip-file
"""
This type stub file was generated by pyright. (Modified by @sakgoyal)
"""

from http.client import HTTPResponse

class Error(Exception):
    """Base error for this module."""

    ...

class HttpError(Error):
    """HTTP data was invalid or unexpected."""
    def __init__(self, resp: HTTPResponse, content: bytes, *, uri: str = ...) -> None: ...
    @property
    def status_code(self) -> int:
        """Return the HTTP status code from the response content."""
        ...
