from Scripts.shared_imports import *
import typing as T

def validate_video_id(
    video_url_or_id,
    silent: bool = ...,
    pass_exception: bool = ...,
    basicCheck: bool = ...,
): ...
def validate_post_id(post_url) -> None: ...
def validate_channel_id(
    inputted_channel: str,
) -> T.Tuple[bool, T.Optional[str], T.Optional[T.Any]]: ...
def validate_regex(regex_from_user: str): ...
def validate_config_settings(config) -> None: ...
